config/routes.rb
Rails.application.routes.draw do

  resources :meal

  root 'home#index'
  devise_for :members

  get 'dashboard' => 'dashboard#index'
  post 'dashboard' => 'meal#create'
  get 'about' => 'home#about'

  get '/profile' => 'profile#index'
  get '/profile/:id', to: 'profile#show', as: 'show_profile'
  get '/profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch '/profile/:id/update', to: 'profile#update', as: 'update_profile'

  # get '/meals/new', to: 'meal#index'
  get '/meals/new', to: 'meal#new'


end

app/models/meal.rb
class Meal < ActiveRecord::Base
	#relationships
	has_many :meal_photos, :dependent => :destroy
	belongs_to :member

  accepts_nested_attributes_for :meal_photos

	#validations
  validates_associated :meal_photos
end

app/models/meal_photo.rb
class MealPhoto < ActiveRecord::Base
	#relationships
	belongs_to :meal

	#paperclip
  has_attached_file :photo, :presence => true,
	:url => "/files/:class/:attachment/:id/:style/:basename.:extension",
	:path => ":rails_root/public/files/:class/:attachment/:id/:style/:basename.:extension",
	:styles  => { :small => "200x200", :large => "1500x1500>" }

	#validations
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def private
    params.require(:meal_photo).permit(:member_id, :photo)
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessor :name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #paperclip
  has_attached_file :photo,
  :url => "/files/:class/:attachment/:id/:style/:basename.:extension",
  :path => ":rails_root/public/files/:class/:attachment/:id/:style/:basename.:extension",
  :styles  => { :small => "200x200#", :large => "700x700>"}, 
  :default_url => ActionController::Base.helpers.asset_path('profile.png')

  #validations
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  #Associations
  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :perl

  protected

  #allows the devise gem to accept firstName, lastName and username
  #variables when a user is creating an account
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :firstName
    devise_parameter_sanitizer.for(:sign_up) << :lastName
  end

  #calls the perl script and saves its data 
  #to meet two server-side technology requirement 
  def perl
    @perltime = `perl "#{Rails.root}/public/time.pl"`
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @meal = Meal.new
    @meals = Meal.all
    @member = current_member
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#function for index.html of this controller
	#root page of the application
	#shows user ether this page or the dashboard if the user is logged in
	def index
		if member_signed_in?
			redirect_to dashboard_path
		end
	end

	#function for about.html of this controller
	#shows the about page which container the user guide
	def about
	end
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  def index
    @meals = Meal.all
  end

  def new
    @meal = Meal.new
    @meal.meal_photos.build
  end

  def create
    @member = current_member
    @meal = current_member.meals.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to dashboard_path, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:member_id, :name, :price, :recipe, :meal_photos_attributes => [:photo])
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	#Functions called each time this controller is invoked before loading 
	before_action :authenticate_member!, only: [:edit, :index]
	before_action :load_params, only: [:show, :edit]
	
	#function for index.html of this controller
	#redirects to the show function
	def index
		redirect_to show_profile_path(current_member.id)
	end

	#function for show.html of this controller
	#loads user and the user meal cards
	def show
		@meals = @member.meals;
	end

	#function for edit.html of this controller
	#lets the user edit his profile 
	def edit 
	end

	#function to handle post request from edit profile 
	#updates the currently logged in user
	def update
		current_member.update(profile_params)

		respond_to do |format|
      		format.html {redirect_to action: 'index'}
     	end
	end

	private

		#load required variables for this controller 
		def load_params
			@member = Member.find(params[:id])
			@member.name = "#{@member.firstName.capitalize} #{@member.lastName.capitalize}"
			
			#redirects user to root url if user is not found
			rescue ActiveRecord::RecordNotFound
				redirect_to(root_url)
		end

		#restricts the model to update only {firstName,lastName,about,photo}
		#variables of the model
		def profile_params
			name = params[:member].extract!(:name)
			name = name[:name].split(" ")

			#prevents nil error
			params[:member][:firstName] = name[0] == nil ? "" : name[0]
			params[:member][:lastName] = name[1] == nil ? "" : name[1]

			params.require(:member).permit(:firstName,
				:lastName,:about,:photo)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meal_helper.rb
module MealHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/dashboard/index.html.erb
<div class="container meals-container">

  <% @meals.each do |meal| %>
    <% member = Member.find(meal.member_id) %>
    <div class="col-lg-6 col-md-4 col-sm-12 meal-container">
      <div class="meal panel">

        <div class="front box1">

          <div class="profile slide-icon">

            <div class="author-bio">
              <h1>
                <span>  
                <%= link_to "#{member.firstName} #{member.lastName}", show_profile_path(member) %>
               </span> added
              </h1>

              <h1 class="name">
                "<%= meal.name %>"
              </h1>

              <h2>
                <%= Member.find(meal.member_id).about %>
              </h2>

              <div class="circle meal-author-photo" style="background-image:url(<%= Member.find(meal.member_id).photo.url %>)"></div>
            </div>

          </div>

          <%= image_tag(meal.meal_photos.first.photo,:class => "meal-photo") %>

          <div class="category">

          </div>
        </div>

        <div class="back box2">

          <h2 class="recipe">
            <%= meal.recipe %>
          </h2>


          <h2 class="price">
            $<%= meal.price %>
          </h2>

        </div>

      </div>
    </div>

  <% end %>

</div>

app/views/home/about.html.erb
<div class="row">
	<div class="col-sm-12">
		<h1 class="title-left">About</h1>
		<p class="about-p">
		This is a project for the CPS530 assignment. Foofly is a social network for food lovers. You can post pictures of your favourite meals along with thier recipes or you can browse and see what others users have posted. Whether you love to take pictures of food or just love looking at food, then this is just the place for you.
		Goodluck and have fun at Foodly :P  
		</p>
	</div> 
</div>
<hr class="divider"/>
<div class="row">
	<div class="col-sm-12">
		<h1 class="title-right">User Guide</h1>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Home page</h1>
			<p class="about-p">Upon visiting the main page of the website, you will be presented with an image with the name of the website on the center of the page, this is the home page. By clicking on the “F” icon on the top left corner of the web page, a sidebar will appear from the left displaying a list of options the user can navigate to from the home page. </p>
		</div>
    </div>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Sign up</h1>
			<p class="about-p">To sign up for Foodly, click on the signup link in the sidebar. Once the signup page loads, enter your name, a valid email address to be used to log in with and password in the appropriate text boxes. Clicking signup on this page will create the account with the entered information and will now allow you to access the rest of the site.</p>
		</div>
    </div>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Login</h1>
			<p class="about-p">To login, click the “F” in the top left of the page to reveal the sidebar. Click on “Login” to be directed to the login page where you will be requested to enter your email and password that you used when creating your profile during the signup process.</p>
		</div>
    </div>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Logout</h1>
			<p class="about-p">To logout of your profile click on the “F” on the top left of the page to reveal the sidebar. Click the logout out button and you will then be signed out of your profile.</p>
		</div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">My Profile</h1>
			<p class="about-p">To view your main profile page you will first be signed into your profile. Once signed to your profile click the “F” on the top left of your page to reveal the sidebar. Click on “My Profile” to be brought to your profile page where you can post new meals and view other meals other users have created.</p>
		</div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Creating a Meal</h1>
			<p class="about-p">To create a meal you need to be signed in and on your “My Profile” page. Once there, click on the “F” on the top left and click create meal. You will now be presented by a new page when you enter the name of your meal, the price of your meal, and finally an image that you can upload to represent your meal. Once you finished entering the information and uploaded an image click Submit to submit your meal to your profile for others to view.</p>
		</div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
		<div class="meal">
			<h1 class="center">Editing your Profile</h1>
			<p class="about-p">To change your profile picture or name, navigate to your “My Profile” Page. On the top right of your profile page, click on the pen icon to edit your profile. Here you will be able to change your name and your profile picture. Type in a new name to change your name, or/and click on upload file to choose a new profile picture, once done click on the checkmark on the top right of the edit page to save your changes.</p>
		</div>
    </div>

</div>
<hr class="divider"/>
<div class="row">
	<div class="col-sm-12"><h1 class="title-left">The Team</h1></div>
	<div class="col-sm-4">
		<div class="about-team">
			<div class="circle team-member-1"></div>
			<label>Igar Liubavetskiy</label>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="about-team">
			<div class="circle team-member-2"></div>
			<label>Vitaliy Krasylovets</label>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="about-team">
			<div class="circle team-member-3"></div>
			<label>Richard Oliveira</label>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<!--<div class="home_image"></div>-->
	<h1 class="title">Foodly</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Foodly</title>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>

  <!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">-->
  <!--<link href='https://fonts.googleapis.com/css?family=Old+Standard+TT:400,400italic,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,100italic,300italic,400italic,700italic' rel='stylesheet' type='text/css'>-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/sidebar" %>
  <div class="container-fluid container-sidebar">
    <div id="sidebar-btn">F</div>
    <%= yield %>
  </div>
</body>
</html>

app/views/meal/new.html.erb
<div class="row">
  <div class="col-md-12 new-meal"> 
      <%= form_for @meal, :url => {:action => 'create'}, :html => { :multipart => true } do |f| %>
        <%= f.label :name %></br>
        <%= f.text_field :name %></br>

        <%= f.label :price %></br>
        <%= f.text_field :price %></br>

        <%= f.label :recipe %></br>
        <%= f.text_area :recipe %></br>

        <%= f.fields_for :meal_photos do |builder| %>
          <%= builder.file_field :photo %>
        <% end %>

        <p>
          <%= f.submit "Create", :class =>"btn"  %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<aside class="sidebar" role="navigation">
	<nav>
    <ul>
        <% if current_page? root_path %>
          <li><%= link_to "Sign up", new_member_registration_path %> </li>
          <li><%= link_to "About", about_path  %></li>
        <% else %> 
          <li><%= link_to "Home", root_path %></li>
          <% if !member_signed_in? %>
            <li><%= link_to "Sign up", new_member_registration_path %> </li>
          <% else %>
            <li><%= link_to "My Profile", show_profile_path(current_member) %></li>
            <li><%= link_to "New Meal", new_meal_path %></li>
          <% end %>
          <li><%= link_to "About", about_path  %></li>
        <% end %>
    </ul>
	</nav>
  <hr class="divider"/>
  <% if member_signed_in? %>
    <%= link_to "Logout", destroy_member_session_path,
                      :method => :delete, :class => "btn-login" %>
  <% else %>
    <%= link_to "Login", member_session_path,:class => "btn-login"  %>
  <% end %>
  <div class="perl"><div>Server Time</div><%= @perltime%></div>
</aside>
<div id="sidebar-overlay" class="sidebar-overlay hidden"></div>